# See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

# This stage is used when running from VS in fast mode (Default for Debug configuration)
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["EV-Station.Api/EV-Station.Api.csproj", "EV-Station.Api/"]
COPY ["EV-Station.Application/EV-Station.Application.csproj", "EV-Station.Application/"]
COPY ["EV-Station.Domain/EV-Station.Domain.csproj", "EV-Station.Domain/"]
COPY ["EV-Station.Infrastructure/EV-Station.Infrastructure.csproj", "EV-Station.Infrastructure/"]
RUN dotnet restore "./EV-Station.Api/EV-Station.Api.csproj"

COPY . .
WORKDIR "/src/EV-Station.Api"
RUN dotnet build "./EV-Station.Api.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./EV-Station.Api.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "EV-Station.Api.dll"]