<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>EV_Station.Application</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="11.1.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Common\Mappings\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EV-Station.Domain\EV-Station.Domain.csproj" />
  </ItemGroup>

</Project>
